# Generated by Django 2.2.4 on 2019-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.CharField(max_length=320)),
                ('determinante', models.BooleanField()),
                ('traco', models.BooleanField()),
                ('transposta', models.BooleanField()),
                ('inversa', models.BooleanField()),
                ('polinomio_caracteristico', models.BooleanField()),
                ('autovalores', models.BooleanField()),
                ('autovetores', models.BooleanField()),
                ('matriz_diagonal', models.BooleanField()),
            ],
        ),
    ]
