# Generated by Django 2.2.4 on 2019-12-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='autovetores',
            field=models.BooleanField(default=False),
        ),
    ]
